# Generated by Django 4.2.22 on 2025-11-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enseignants",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=128)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="cours",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cours_images/"),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cours.enseignants",
                    ),
                ),
            ],
        ),
    ]
