# Generated by Django 4.2.22 on 2025-11-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cours",
            name="enseignant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cours.enseignants",
            ),
        ),
    ]
