# Generated by Django 4.2.22 on 2025-12-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0002_alter_cours_enseignant"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="montant",
            field=models.DecimalField(decimal_places=2, default=20.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cours",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cours",
            name="enseignant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cours.enseignants",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                (
                    "mot_de_passe",
                    models.CharField(
                        default="pbkdf2_sha256$600000$lgmp80aSHojZM8C1cGJnqE$KgW/M0PMHpJEA7MuxEDsnwNdCCxQ2GxPxm+ohHpfHC4=",
                        max_length=128,
                    ),
                ),
                ("payment_id", models.CharField(blank=True, max_length=255, null=True)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="cours.cours",
                    ),
                ),
            ],
            options={
                "unique_together": {("cours", "email")},
            },
        ),
    ]
