# Generated by Django 4.2.22 on 2025-12-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0003_cours_montant_alter_cours_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="user",
            name="statut",
            field=models.CharField(default="en_attente", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$Ro3lnJcduxZEBm7aA2r1YO$+m1g68sIAOrjrUE6Tdg+iSRPJ13jpPgufQFLGnfD+78=",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_id", models.CharField(max_length=255)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("statut", models.CharField(default="réussi", max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "inscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="cours.user"
                    ),
                ),
            ],
        ),
    ]
