# Generated by Django 4.2.22 on 2025-12-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0004_remove_user_payment_id_user_statut_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paiement",
            old_name="inscription",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$Cq7NP2b4alCkkfd1NMcPBC$zPE3pFwUNEX2eeuiruPX63OlJt2hPowufGYIFZBYuzo=",
                max_length=128,
            ),
        ),
    ]
