# Generated by Django 4.2.22 on 2026-01-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0005_rename_inscription_paiement_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$OEY8ccRmvPuO25t8m9F0RF$vze7Nz07qe8A8rjv9qvigb6KwWzd3JgaEv0lGcQ59pQ=",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="CoursePreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video", models.FileField(upload_to="courses/previews/")),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previews",
                        to="cours.cours",
                    ),
                ),
            ],
        ),
    ]
