# Generated by Django 4.2.22 on 2026-02-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0006_alter_user_mot_de_passe_coursepreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=255)),
                ("video", models.FileField(upload_to="videos/")),
                ("is_preview", models.BooleanField(default=False)),
                ("ordre", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=255)),
                ("ordre", models.IntegerField(default=0)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cours.cours",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$fMCQ0QGNQz4tRsV18mTUvC$ivmEuRKpIhmoUq03mqufGFDucLFIzuS9haPgSJxTMeQ=",
                max_length=128,
            ),
        ),
        migrations.DeleteModel(
            name="CoursePreview",
        ),
        migrations.AddField(
            model_name="lecon",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecons",
                to="cours.section",
            ),
        ),
    ]
