# Generated by Django 4.2.22 on 2026-02-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0007_lecon_section_alter_user_mot_de_passe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Utilisateurs", "Utilisateurs"), ("Admin", "Admin")],
                default="Utilisateurs",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$GJwt2xnmP4gWgIvKll3cLL$JFIzc6nutXLMqluVGD4zxJVHLDNJGCXj/PmWe+0TiBE=",
                max_length=128,
            ),
        ),
    ]
