# Generated by Django 4.2.22 on 2026-02-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0008_user_role_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$odPbzedSr3EyvkJy1xwq5N$2LmIlJ7OmEpNlyHdoj6urHgryLIYzBJI3IvikxY1h0U=",
                max_length=128,
            ),
        ),
    ]
