# Generated by Django 4.2.22 on 2026-02-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0009_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$rrAJA9tV27gDnE4mQ86qN0$LBB1t/LqyJl90BF8Q4czzNKW5/yMgOBUL79zFW9lgKo=",
                max_length=128,
            ),
        ),
    ]
