# Generated by Django 4.2.22 on 2026-02-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0010_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$mMAPVIjXBA00RYmZu6BB0L$mJ9EhEFYnBy9Gk6ABDVnrwh/cNmPaITkC3m1htMfgyY=",
                max_length=128,
            ),
        ),
    ]
