# Generated by Django 4.2.22 on 2026-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0011_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$U6RNdPjpB0yXgrmkS6S2tu$mb9LQJ5IJQyT321w1WF7mnq9h9SLrDWJEL1P20W5gn8=",
                max_length=128,
            ),
        ),
    ]
