# Generated by Django 4.2.22 on 2026-02-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0012_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$NhG8XcJqimGyqLdeYTVYAa$0KOEIYb/q/bGw2J8By7UxrDQ4R39tJqm5JwJoGhPSUI=",
                max_length=128,
            ),
        ),
    ]
