# Generated by Django 4.2.22 on 2026-02-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0013_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$fkvxODImJiya2Ln4quQvuW$sjbn1ggQjG1+/DzZRwnhYhQDJxy9fKVjCPWpw0fskJQ=",
                max_length=128,
            ),
        ),
    ]
