# Generated by Django 4.2.22 on 2026-02-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0014_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$gF2cHeCOxd63FYh24koaeg$/RD+TR3MkQABYpyycR7DQLrGt8yrcMeIyRiL6H19lws=",
                max_length=128,
            ),
        ),
    ]
