# Generated by Django 4.2.22 on 2026-02-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0015_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$PwECRy4hvQurlxTDGPZWXN$D3RHAp8SLAF9j7l+uXYNQ5TFNhLzNseMBJLwT9qmwJQ=",
                max_length=128,
            ),
        ),
    ]
