# Generated by Django 4.2.22 on 2026-02-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0016_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$Qz51F3h2m87VLRBDQVNG1O$A6NhFJkL9m78IY7LP67Up4Jo6FF6fTB5pete/usnT88=",
                max_length=128,
            ),
        ),
    ]
