# Generated by Django 4.2.22 on 2026-02-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0017_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$0jpGv2HKi9n2mDQKTaKPLi$gcE1W1PBEtd3sRw2Z7Z6rMwt3Y4l8pG9olaKZqFYcTk=",
                max_length=128,
            ),
        ),
    ]
