# Generated by Django 4.2.22 on 2026-02-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0018_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$kaOA0TKtd6GJjDxnrKEl6J$gN2UeUKFFvBAzsWNzms//4I4FC1H1f0p7lHP4PZB6Kg=",
                max_length=128,
            ),
        ),
    ]
