# Generated by Django 4.2.22 on 2026-02-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0019_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$DyPWZUXtAEfCSKxit7ekYI$KpOpOQa6ke1iKK6OFPbJ6FS+MyHjWGtKICDOE2a//Q8=",
                max_length=128,
            ),
        ),
    ]
