# Generated by Django 4.2.22 on 2026-02-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0020_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$CzhBFJvjM3QwM7xAqiLGZz$C0rmLSH7zy6sDzACLE8h6fgBbpOSQJKFsQP0uh0UiQ4=",
                max_length=128,
            ),
        ),
    ]
