# Generated by Django 4.2.22 on 2026-02-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0021_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$EubUCFzJfKzNAxQe9Xe8Ns$3J3yoWa65h94GOVR21uraqzmDj+DHZ8iGFTrzqoqAww=",
                max_length=128,
            ),
        ),
    ]
