# Generated by Django 4.2.22 on 2026-02-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0022_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$ipsnnL7gFO8kDfruhuGdL0$i+DU9zq3bQ1lt0YY2EMTgloFuNShXYLxPhQOnvJWihA=",
                max_length=128,
            ),
        ),
    ]
