# Generated by Django 4.2.22 on 2026-02-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0023_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$MMYhar2mNZa7U0bXspI1qy$wVMa1dwO+csEplZNGy4fC3hsd4RWlcUAhqEXS/sa3aA=",
                max_length=128,
            ),
        ),
    ]
