# Generated by Django 4.2.22 on 2026-02-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0024_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$c4zznvQvfboBA50w7mFbe9$2yyUBIE2FYzOIkJ83nb7RXLudiGEjAaOUnHZ0DCUBwg=",
                max_length=128,
            ),
        ),
    ]
