# Generated by Django 4.2.22 on 2026-02-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0025_alter_user_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$6n3QD2PzgD0R9ZWd2ejlRs$xDpywc7GGEcMqYH+OuhBthc/q6nKu9MFAOk26/oOtVU=",
                max_length=128,
            ),
        ),
    ]
